[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
  "requirements.txt",
  "src/**",
  "railway.toml",
  "Dockerfile"
]

[deploy]
startCommand = "python src/manage.py migrate && gunicorn demo_saas.wsgi"